#!/bin/bash

header()
{
	FILE=$1
	VAR=$2

	/usr/bin/xxd -i ${FILE} | sed 's/'${FILE}'/'${VAR}'/'
}

cd asm
make clean
PATH=../cc65-2.13.3/bin:$PATH make

(
header autoload autoload1333 4
header inflate inflatecode 8
header fastload9600 fastload9600 4
header fastload8000 fastload8000 4
header fastloadcd fastloadcd 4
header fastload15k fastload15k
header diskload9600 diskload9600 4
header diskload8000 diskload8000 4
header diskload15k diskload15k
header diskload2 diskloadcode2 8
header diskload3 diskloadcode3 8
) > ../c2t.h.1

cd ..

monheader()
{
	FILE=$1
	VAR=$2
	COMMENT=$3

	echo ""
	echo "// ${COMMENT}"
	echo "unsigned char ${VAR}[] = {"
	cat ${FILE} | \
		sed 's/ /,0x/g' | \
		sed 's/$/,/' | \
		sed -E 's/^(..*:)./\t\/*\1*\/ /'
	echo "};"
}

(
#monheader mon/dos33.boot1.mon dosboot1 "DOS 3.3 page 3 vectors"
#monheader mon/dos33.boot2.mon dosboot2 "DOS 3.3 boot 2"
monheader mon/dos33.rwts.mon dosrwts "DOS 3.3 RWTS rip"
) > c2t.h.2

incheader()
{
	FILE=$1

	echo ""
	cat ${FILE} \
		| sed -n '/;[[:space:]]*--END-OF-H/q; p;' \
		| sed 's/;/\/\//' \
		| sed -E 's|[[:space:]]*([[:alnum:]_]+)[[:space:]]*=[[:space:]]*(.+)|#define \1 \2|' \
		| sed 's/[[:space:]]\$/ 0x/'
}

(
incheader asm/autoload.inc
incheader asm/inflate.inc
incheader asm/fastload.inc
incheader asm/diskload1.inc
incheader asm/diskload2.inc
incheader asm/diskload3.inc
incheader asm/dosrwts.inc
) > c2t.h.3

cat c2t.h.[0123] > c2t.h

rm -f c2t.h.[123]
